### ISSUE TITLE
Determinate Circular Progress

### ISSUE THREAD

**Issue by rizlas** [dminta/MaterialProgressBarXamarinAndroidBinding#1]
Determinate Circular ProgressBar is not showing in android 4.4.4.
```
                                        ProgressBar = frame.FindViewById<MaterialProgressBar>(Resource.Id.AdPbMaterialProgressBar);
                                        ProgressBar.Indeterminate = false;
                                        ProgressBar.Max = 100;
                                        ProgressBar.Progress = 50;
```

**Comment by dminta** [comment]
You didn't provide information about your layout and styles. Run Sample project on your device and check if Determinate Circular ProgressBar is showing - if not, please provide simple project which reproduces your issue.

**Comment by rizlas** [comment]
<me.zhanghai.android.materialprogressbar.MaterialProgressBar
      android:layout_width="wrap_content"
      android:layout_height="wrap_content"
      android:layout_gravity="left|bottom"
      android:id="@+id/AdPbMaterialProgressBar"
      style="@style/Widget.MaterialProgressBar.ProgressBar" />

maybe the style field is wrong?

**Comment by dminta** [comment]
```
<me.zhanghai.android.materialprogressbar.MaterialProgressBar
android:layout_width="wrap_content"
android:layout_height="wrap_content"
android:layout_gravity="left|bottom"
android:indeterminate="false"
android:id="@+id/AdPbMaterialProgressBar"
style="@style/Widget.MaterialProgressBar.ProgressBar" />
```
